; -*-Lisp-*-
;;============================================================ 
;; please define emacs-where when calling this script
;;============================================================ 
;(setq emacs-where "~/repository/linux/emacs")
;(setq emacs-where "C:/git/conf/emacs")
;(setq default-directory (concat emacs-where "/"))
;(add-to-list 'load-path (concat emacs-where "/site-lisp"))
;(load-file (concat emacs-where "/_emacs"))

;;============================================================ 
;; editor misc
;;============================================================ 
;; no startup information
(setq inibit-startup-message t)
(setq inhibit-splash-screen t)
(setq gnus-inibit-startup-message t)
;; no backup
(setq-default make-backup-files nil)
;; syntax hight
(global-font-lock-mode t)
(setq lazy-lock-defer-on-scrolling t)
(setq font-lock-maximum-decoration t)
;; line number
(global-linum-mode t)
;; clipboard
(setq x-select-enable-clipboard t)
(set-clipboard-coding-system 'ctext)
;; block
(cua-mode t)
;; '_' as part of word
(modify-syntax-entry ?_ "w")
;; highlight block selection
(transient-mark-mode t)

(show-paren-mode t)
(setq show-paren-style 'parentheses)

(mouse-avoidance-mode 'animate)
(setq mouse-yank-at-point t)

(setq default-line-spacing 4)
;; (setq default-fill-column 60)
(setq default-major-mode 'text-mode)
(setq kill-ring-max 200)
(setq require-final-newline t)
(setq-default truncate-partial-width-windows nil)
;; turn off auto-fill
(turn-off-auto-fill)
(auto-fill-mode -1)
(remove-hook 'text-mode-hook 'turn-on-auto-fill)
;;============================================================ 
;; evil
;;============================================================ 
(add-to-list 'load-path (concat emacs-where "/site-lisp/evil"))
(require 'evil)
(evil-mode 1)

;;============================================================ 
;; ibuffer
;;============================================================ 
(require 'ibuffer)
(global-set-key (kbd "C-x C-b") 'ibuffer)

;;============================================================ 
;; color theme
;;============================================================ 
(require 'color-theme)
;(color-theme-pierson)
(color-theme-dark-laptop)

;;============================================================ 
;; tramp
;; tramp can be used link C-x C-f
;; /plink:user@host:/path/to/your/file
;;============================================================ 
(require 'tramp)
(setq tramp-default-method "plink")

;;============================================================ 
;; other plugin
;;============================================================ 
(require 'browse-kill-ring)
(global-set-key [(control c)(k)] 'browse-kill-ring)
(browse-kill-ring-default-keybindings)

;;============================================================ 
;; file type
;;============================================================ 
;; matlab mode
(autoload 'matlab-mode "matlab" "Enter Matlab mode." t)
(setq auto-mode-alist 
  (cons '("\\.m$" . matlab-mode) auto-mode-alist))
(defun my-matlab-mode-hook ()
  (setq matlab-indent-function t)
  (turn-off-auto-fill))
(setq matlab-mode-hook 'my-matlab-mode-hook)
(autoload 'matlab-shell "matlab" "Interactive Matlab mode." t)
(defun my-matlab-shell-mode-hook () 
 '())
(setq matlab-mode-hook 'my-matlab-mode-hook)
